from app.services.coach_agent import CoachAgent
from app.schemas.orchestrator import ConversationContext

def test_generate_summary_with_api_key(mocker):
    # 1. Mock the environment variable
    mocker.patch.dict("os.environ", {"LLM_API_KEY": "test-key"})

    # 2. Create a CoachAgent and a ConversationContext
    coach_agent = CoachAgent()
    context = ConversationContext(
        session_id="test-session",
        current_document={"text": "This is a test document."}
    )

    # 3. Call the generate_summary function
    summary = coach_agent.generate_summary(context)

    # 4. Assert the result
    assert summary == "This is a summary generated by a large language model."

def test_generate_summary_without_api_key(mocker):
    # 1. Mock the environment variable
    mocker.patch.dict("os.environ", clear=True)

    # 2. Create a CoachAgent and a ConversationContext
    coach_agent = CoachAgent()
    context = ConversationContext(
        session_id="test-session",
        current_document={"text": "This is a test document."}
    )

    # 3. Call the generate_summary function
    summary = coach_agent.generate_summary(context)

    # 4. Assert the result
    assert summary == "LLM_API_KEY not set."

def test_generate_flashcards_with_api_key(mocker):
    # 1. Mock the environment variable
    mocker.patch.dict("os.environ", {"LLM_API_KEY": "test-key"})

    # 2. Create a CoachAgent and a ConversationContext
    coach_agent = CoachAgent()
    context = ConversationContext(
        session_id="test-session",
        current_document={"text": "This is a test document."}
    )

    # 3. Call the generate_flashcards function
    flashcards = coach_agent.generate_flashcards(context)

    # 4. Assert the result
    assert flashcards == [
        {"question": "What is the capital of France?", "answer": "Paris"},
        {"question": "What is 2 + 2?", "answer": "4"}
    ]

def test_generate_quiz_with_api_key(mocker):
    # 1. Mock the environment variable
    mocker.patch.dict("os.environ", {"LLM_API_KEY": "test-key"})

    # 2. Create a CoachAgent and a ConversationContext
    coach_agent = CoachAgent()
    context = ConversationContext(
        session_id="test-session",
        current_document={"text": "This is a test document."}
    )

    # 3. Call the generate_quiz function
    quiz = coach_agent.generate_quiz(context)

    # 4. Assert the result
    assert quiz == [
        {
            "question": "What is the capital of France?",
            "options": ["London", "Berlin", "Paris", "Madrid"],
            "correct_answer": "Paris"
        },
        {
            "question": "What is 2 + 2?",
            "options": ["3", "4", "5", "6"],
            "correct_answer": "4"
        }
    ]

