import os
from typing import List
from app.schemas.orchestrator import ConversationContext

class CoachAgent:
    """
    The Coach Agent is responsible for generating study materials
    like summaries, flashcards, and quizzes.
    """

    def generate_summary(self, context: ConversationContext) -> str:
        """
        Generates a summary of the document in the conversation context.
        """
        raw_text = context.current_document.get("text", "") if context.current_document else ""
        if not raw_text:
            return "The document is empty."

        # In a real implementation, this would call an LLM.
        # We will simulate this call.
        api_key = os.environ.get("LLM_API_KEY")
        if not api_key:
            return "LLM_API_KEY not set."

        # Simulate LLM call

        
        # Simulated response
        summary = "This is a summary generated by a large language model."

        return summary

    def generate_flashcards(self, context: ConversationContext) -> List[dict]:
        """
        Generates flashcards from the document in the conversation context.
        """
        raw_text = context.current_document.get("text", "") if context.current_document else ""
        if not raw_text:
            return []

        # In a real implementation, this would call an LLM.
        # We will simulate this call.
        api_key = os.environ.get("LLM_API_KEY")
        if not api_key:
            return []

        # Simulate LLM call

        
        # Simulated response
        flashcards = [
            {"question": "What is the capital of France?", "answer": "Paris"},
            {"question": "What is 2 + 2?", "answer": "4"}
        ]

        return flashcards

    def generate_quiz(self, context: ConversationContext) -> List[dict]:
        """
        Generates a quiz from the document in the conversation context.
        """
        raw_text = context.current_document.get("text", "") if context.current_document else ""
        if not raw_text:
            return []

        # In a real implementation, this would call an LLM.
        # We will simulate this call.
        api_key = os.environ.get("LLM_API_KEY")
        if not api_key:
            return []

        # Simulate LLM call

        
        # Simulated response
        quiz = [
            {
                "question": "What is the capital of France?",
                "options": ["London", "Berlin", "Paris", "Madrid"],
                "correct_answer": "Paris"
            },
            {
                "question": "What is 2 + 2?",
                "options": ["3", "4", "5", "6"],
                "correct_answer": "4"
            }
        ]

        return quiz

    def process(self, context: ConversationContext, instruction: str) -> ConversationContext:
        """
        Processes the user's instruction and returns the updated context.
        """
        if instruction == "generate_summary":
            summary = self.generate_summary(context)
            context.history.append({
                "agent": "coach_agent",
                "summary": summary
            })
            context.last_agent_used = "coach_agent"
        
        elif instruction == "generate_flashcards":
            flashcards = self.generate_flashcards(context)
            context.history.append({
                "agent": "coach_agent",
                "flashcards": flashcards
            })
            context.last_agent_used = "coach_agent"

        elif instruction == "generate_quiz":
            quiz = self.generate_quiz(context)
            context.history.append({
                "agent": "coach_agent",
                "quiz": quiz
            })
            context.last_agent_used = "coach_agent"

        return context
